@startuml "Publish a Composite Datastream"
actor ProducerOrganization
actor ConsumerOrganization1
actor ConsumerOrganizationN

group Prerequisite
ProducerOrganization    <- ThingBook: Subscribe <<SensorThings>>
end
ProducerOrganization    -> ThingBook : Observation <<SensorThings>>
ConsumerOrganization1    <- ThingBook : Observation <<SensorThings>>
ConsumerOrganizationN    <- ThingBook : Observation <<SensorThings>>

hide footbox
@enduml
